version: "3"

services:
  redis:
    image: redis:4.0.6
    command: ["--appendonly", "yes", "--requirepass", "Abcd@1234"]
    volumes:
      - /goc_automation_platform_docker/compose/redis/data:/data
      #- /goc_automation_platform_docker/compose/redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    expose:
      - "6379"
    restart: always
  
  mysql:
    image: mysql:5.7.39
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Abcd@1234
      - MYSQL_DATABASE=GOCAutomation_DB
    volumes:
      - /goc_automation_platform_docker/compose/mysql/data:/var/lib/mysql # 挂载数据库数据
      - /goc_automation_platform_docker/compose/mysql/conf/my.cnf:/etc/my.cnf # 挂载配置文件
      - /goc_automation_platform_docker/compose/mysql/logs:/var/log/mysql # 挂载日志
    restart: always
  
  web:
    image: goc_automation_web:1.2
    ports:
      - "9999:9999"
    expose:
      - "9999"
    volumes:
      - /net/szhvm00574/fs0/gocautomation_site/goc_automation:/goc_automation # 挂载项目代码
    environment:
      - DEBUG=False
    restart: always
    depends_on:
      - mysql
      - redis
    tty: true
    stdin_open: true

  nginx:
    image: nginx:1.14.1
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - /net/szhvm00574/fs0/gocautomation_site/goc_automation:/goc_automation # 挂载项目代码
      - /goc_automation_platform_docker/compose/nginx/log:/var/log/nginx # 挂载日志
      - /goc_automation_platform_docker/compose/nginx/nginx.conf:/etc/nginx/nginx.conf # 挂载配置文件
    depends_on:
      - web
    restart: always
