services:
  dns:
    - 10.54.12.44
    - 10.187.50.203
  web:
    build: .
    command: 'python manage.py runserver 0.0.0.0:8111'
    ports:
      - "8111:8111"
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost