version: "3"

services:
  redis:
    image: redis:4.0.6
    command: ["--appendonly", "yes", "--requirepass", "Abcd@1234"]
    volumes:
      - /goc_automation_platform_docker/compose/redis/data:/data
      #- /goc_automation_platform_docker/compose/redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "6380:6380"
    expose:
      - "6380"
    restart: always
  
  db:
    image: mysql:8.0
    container_name: mysql_goc
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'goc'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    ports:
      - "3307:3307"
  
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:9999"
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_URL=mysql://root:123456@db:3307/goc
    ports:
      - "9999:9999"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true

  nginx:
    image: nginx:1.14.1
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - /net/szhvm00574/fs0/gocautomation_site/goc_automation:/app # 挂载项目代码
      - /goc_automation_platform_docker/compose/nginx/log:/var/log/nginx # 挂载日志
      - /goc_automation_platform_docker/compose/nginx/nginx.conf:/etc/nginx/nginx.conf # 挂载配置文件
    depends_on:
      - web
    restart: always
