version: "3"

services:
  redis:
    image: redis:4.0.6
    command: ["--appendonly", "yes", "--requirepass", "Abcd@1234"]
    volumes:
      - /var/lib/jenkins/workspace/redis/data:/data
      #- /goc_automation_platform_docker/compose/redis/conf/redis.conf:/etc/redis/redis.conf
    ports:
      - "6380:6380"
    expose:
      - "6380"
    restart: always
    networks:
      - my_network
  
  db:
    image: mysql:8.0
    container_name: mysql_goc
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'goc'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
    ports:
      - "3307:3307"
    networks:
      - my_network
  
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:9999"
    volumes:
      - .:/app
      - /var/lib/jenkins/workspace:/var/lib/jenkins/workspace
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_URL=mysql://root:123456@db:3307/goc
    ports:
      - "9999:9999"
    expose:
      - "9999"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    networks:
      - my_network

#  nginx:
#    image: nginx:1.14.1
#    ports:
#      - "80:80"
#    expose:
#      - "80"
#    volumes:
#      - .:/app # 挂载项目代码
#      - /var/lib/jenkins/workspace/logs/:/var/log/nginx/ # 挂载日志
#      - /var/lib/jenkins/workspace/nginx.conf/:/etc/nginx/ # 挂载配置文件
#    depends_on:
#      - web
#    restart: always
#    networks:
#      - my_network

networks:
  my_network:
    driver: bridge