# Generated by Django 3.2.15 on 2024-10-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMCActivities',
            fields=[
                ('pmc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='PMC ID')),
                ('data_status', models.IntegerField(default=1, verbose_name='Data status')),
                ('itsp_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ITSP No')),
                ('data_center_room', models.CharField(max_length=100, verbose_name='Data center room')),
                ('change_class', models.IntegerField(default=0, verbose_name='Change class')),
                ('reason', models.CharField(max_length=500, verbose_name='Reason')),
                ('start_time', models.IntegerField(verbose_name='Start time')),
                ('end_time', models.IntegerField(verbose_name='End time')),
                ('start_with_shutdown', models.CharField(max_length=20, verbose_name='Start with shutdown')),
                ('region', models.CharField(max_length=20, verbose_name='Region')),
                ('location_code', models.CharField(max_length=20, verbose_name='Location code')),
                ('additional_people', models.CharField(blank=True, max_length=200, null=True, verbose_name='Additional people')),
                ('people_onsite', models.CharField(max_length=200, verbose_name='People onsite')),
                ('engineer_address', models.CharField(max_length=200, verbose_name='Engineer address')),
                ('contact_information', models.CharField(max_length=200, verbose_name='Contact information')),
                ('change_number', models.CharField(max_length=40, verbose_name='Change number')),
                ('status', models.IntegerField(verbose_name='Status')),
                ('power_off_assignee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Power off assignee')),
                ('power_on_assignee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Power on assignee')),
                ('san_vnx', models.IntegerField(default=0, verbose_name='SAN VNX')),
                ('san_unity', models.IntegerField(default=0, verbose_name='SAN Unity')),
                ('san_vplex', models.IntegerField(default=0, verbose_name='SAN VPLEX')),
                ('nas', models.IntegerField(default=0, verbose_name='NAS')),
                ('backup', models.IntegerField(default=0, verbose_name='Backup')),
                ('oracle_db', models.IntegerField(default=0, verbose_name='Oracle DB')),
                ('email_notification', models.IntegerField(default=0, verbose_name='Email Notification')),
                ('high_availability', models.IntegerField(default=0, verbose_name='High availability')),
                ('server_room_to_failover', models.CharField(blank=True, max_length=200, null=True, verbose_name='Server room to failover')),
                ('service_to_failover', models.CharField(blank=True, max_length=200, null=True, verbose_name='service to failover')),
                ('backup_assignee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Backup assignee')),
                ('oracle_db_assignee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Oracle DB assignee')),
                ('pmc_coordinator', models.CharField(blank=True, max_length=100, null=True, verbose_name='PMC coordinator')),
            ],
            options={
                'verbose_name': 'PMC Activities',
                'verbose_name_plural': 'PMC Activities',
                'db_table': 'pmc_activities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PMCActivityplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc_id', models.IntegerField(default=0, verbose_name='PMC ID')),
                ('line_number', models.IntegerField(default=0, verbose_name='Line number')),
                ('date_start', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date start')),
                ('start_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Start time')),
                ('description_of_activity', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description of activity')),
                ('execution', models.CharField(blank=True, max_length=500, null=True, verbose_name='Execution')),
                ('responsible', models.CharField(blank=True, max_length=500, null=True, verbose_name='Responsible')),
                ('information_to', models.CharField(blank=True, max_length=500, null=True, verbose_name='Start time')),
            ],
            options={
                'verbose_name': 'PMC Activity Plan',
                'verbose_name_plural': 'PMC Activity Plan',
                'db_table': 'pmc_activity_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PMCAssignee',
            fields=[
                ('assignee_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Assignee ID')),
                ('assignee_nt', models.CharField(max_length=20, verbose_name='Assignee NT account')),
                ('assignee_name', models.CharField(max_length=100, verbose_name='Assignee Name')),
                ('assignee_department', models.CharField(max_length=100, verbose_name='Assignee Department')),
                ('assignee_email', models.CharField(max_length=100, verbose_name='Assignee Email')),
                ('assignee_responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assignee Responsible')),
            ],
            options={
                'verbose_name': 'PMC Assignee',
                'verbose_name_plural': 'PMC Assignee',
                'db_table': 'pmc_assignee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PMCDevicelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc_id', models.IntegerField(default=0, verbose_name='PMC ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('ilo_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='ILO IP')),
                ('vcenter', models.CharField(blank=True, max_length=100, null=True, verbose_name='vCenter')),
                ('data_center_room', models.CharField(blank=True, max_length=100, null=True, verbose_name='DCR')),
                ('ci_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='CI Type')),
                ('tier_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tier 2')),
                ('tier_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tier 3')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('support_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Support group')),
            ],
            options={
                'verbose_name': 'PMC Device List',
                'verbose_name_plural': 'PMC Device List',
                'db_table': 'pmc_device_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PMCOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmc_id', models.IntegerField(default=0, verbose_name='PMC ID')),
                ('pmc_confirmed', models.IntegerField(default=0, verbose_name='PMC Confrimed')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('ilo_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='ILO IP')),
                ('vcenter_fqdn', models.CharField(blank=True, max_length=100, null=True, verbose_name='vCenter FQDN')),
                ('esx_flag', models.IntegerField(default=0, verbose_name='ESX Flag')),
                ('nas_cluster_flag', models.IntegerField(default=0, verbose_name='NAS Cluster Flag')),
            ],
            options={
                'verbose_name': 'PMC Operation',
                'verbose_name_plural': 'PMC Operation',
                'db_table': 'pmc_operation',
                'managed': True,
            },
        ),
    ]
