# Generated by Django 3.2.15 on 2024-10-12 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmcweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMCBackupschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='Schedule ID')),
                ('change_number', models.CharField(max_length=40, verbose_name='Change number')),
                ('backup_device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('start_time', models.IntegerField(verbose_name='Start time')),
                ('end_time', models.IntegerField(verbose_name='End time')),
                ('schedule_status', models.IntegerField(default=1, verbose_name='Schedule Status')),
                ('pmc_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_schedule', to='pmcweb.pmcactivities')),
            ],
            options={
                'verbose_name': 'PMC Backup Schedule',
                'verbose_name_plural': 'PMC Backup Schedule',
                'db_table': 'pmc_backup_schedule',
                'managed': True,
            },
        ),
    ]
