# Generated by Django 3.2.15 on 2024-11-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmcweb', '0002_pmcbackupschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmcactivities',
            name='san_assignee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SAN assignee'),
        ),
    ]
