# Generated by Django 3.2.15 on 2024-08-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Host ID')),
                ('host_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Host Name')),
                ('dns_domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='DNS Domain')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status')),
                ('status_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Reason')),
                ('os_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='OS Type')),
                ('used_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Used By')),
            ],
            options={
                'verbose_name': 'Host Information',
                'verbose_name_plural': 'Host Information',
                'db_table': 'host_info',
                'managed': True,
            },
        ),
    ]
