# Generated by Django 3.2.15 on 2024-08-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('loginid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Login ID')),
                ('loginpwd', models.CharField(max_length=200, verbose_name='Login Password')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('status', models.BooleanField(default=0, verbose_name='Status')),
                ('admin', models.BooleanField(default=0, verbose_name='Admin')),
                ('pmc_coordinator', models.BooleanField(default=0, verbose_name='PMC coordinator')),
                ('pmc_operator', models.BooleanField(default=0, verbose_name='PMC operator')),
                ('guest_account', models.BooleanField(default=0, verbose_name='Guest account')),
                ('department', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Department')),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Location')),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Email address')),
                ('avatar', models.ImageField(default='empty.empty', null=True, upload_to='avatar', verbose_name='Avatar')),
                ('last_login', models.IntegerField(blank=True, default=None, null=True, verbose_name='Last login')),
                ('create_time', models.IntegerField(blank=True, default=1723770771, null=True, verbose_name='Create time')),
                ('edit_time', models.IntegerField(blank=True, default=None, null=True, verbose_name='Modify time')),
            ],
            options={
                'verbose_name': 'User Accounts',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'user_account',
                'managed': True,
            },
        ),
    ]
