# Generated by Django 3.2.15 on 2024-08-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0002_auto_20240816_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='guest_account',
            field=models.BooleanField(default=0, verbose_name='Guest account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='create_time',
            field=models.IntegerField(blank=True, default=1723771602, null=True, verbose_name='Create time'),
        ),
    ]
