# Generated by Django 4.2.14 on 2024-12-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0009_alter_account_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_time',
            field=models.IntegerField(blank=True, default=1733905243, null=True, verbose_name='Create time'),
        ),
    ]
