# Generated by Django 3.2.15 on 2024-11-16 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0009_alter_account_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, unique=True, verbose_name='Menu Tittle')),
                ('icon', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Menu Icon')),
                ('order', models.IntegerField(blank=True, default=1, null=True, verbose_name='Menu Order')),
            ],
            options={
                'verbose_name': 'User Menu',
                'verbose_name_plural': 'User Menu',
                'db_table': 'user_menu',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='create_time',
            field=models.IntegerField(blank=True, default=1731723469, null=True, verbose_name='Create time'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Role Name')),
                ('desc', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Description')),
                ('account', models.ManyToManyField(null=True, to='userweb.Account', verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Role',
                'db_table': 'user_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, verbose_name='Permission Tittle')),
                ('url', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='URL')),
                ('order', models.IntegerField(blank=True, default=1, null=True, verbose_name='Permission Order')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='userweb.menu', verbose_name='Menu')),
                ('roles', models.ManyToManyField(blank=True, default=None, null=True, to='userweb.Role', verbose_name='User Role')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permission',
                'db_table': 'user_permission',
                'managed': True,
            },
        ),
    ]
