# Generated by Django 4.2.14 on 2024-12-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0010_alter_account_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_time',
            field=models.IntegerField(blank=True, default=1734315037, null=True, verbose_name='Create time'),
        ),
    ]
