# Generated by Django 3.2.15 on 2024-11-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0010_auto_20241116_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.AddField(
            model_name='account',
            name='timezone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='create_time',
            field=models.IntegerField(blank=True, default=1731850613, null=True, verbose_name='Create time'),
        ),
    ]
