# Generated by Django 3.2.15 on 2024-11-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userweb', '0011_auto_20241117_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_time',
            field=models.IntegerField(blank=True, default=1732171813, null=True, verbose_name='Create time'),
        ),
    ]
