# Generated by Django 3.2.15 on 2024-08-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIVisitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, verbose_name='Service name')),
                ('api_url', models.CharField(max_length=200, verbose_name='API url')),
                ('request_amount', models.IntegerField(verbose_name='Request amount')),
                ('request_time', models.IntegerField(default=1723770771, verbose_name='Request time')),
            ],
            options={
                'verbose_name': 'API Visit Statistics',
                'verbose_name_plural': 'API Visit Statistics',
                'db_table': 'api_visit_statistics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppVisitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='Service name')),
                ('app_url', models.CharField(max_length=200, verbose_name='API url')),
                ('request_amount', models.IntegerField(verbose_name='Request amount')),
                ('statistic_time', models.IntegerField(default=1723770771, verbose_name='Statistic time')),
            ],
            options={
                'verbose_name': 'App Visit Statistics',
                'verbose_name_plural': 'App Visit Statistics',
                'db_table': 'app_visit_statistics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HostsStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_type', models.CharField(max_length=100, verbose_name='OS type')),
                ('quantity', models.IntegerField(verbose_name='Host quantity')),
                ('statistic_time', models.IntegerField(default=1723770771, verbose_name='Statistic time')),
            ],
            options={
                'verbose_name': 'Hosts Statistics',
                'verbose_name_plural': 'Hosts Statistics',
                'db_table': 'hosts_statistics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimeSavingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100, verbose_name='Service name')),
                ('time_saved', models.IntegerField(verbose_name='Time saved')),
                ('request_time', models.IntegerField(default=1723770771, verbose_name='Request time')),
            ],
            options={
                'verbose_name': 'Time Saving Statistics',
                'verbose_name_plural': 'Time Saving Statistics',
                'db_table': 'time_saving_statistics',
                'managed': True,
            },
        ),
    ]
