# Generated by Django 4.2.14 on 2024-12-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0009_auto_20241010_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apivisitstatistics',
            name='request_time',
            field=models.IntegerField(default=1733905243, verbose_name='Request time'),
        ),
        migrations.AlterField(
            model_name='appvisitstatistics',
            name='statistic_time',
            field=models.IntegerField(default=1733905243, verbose_name='Statistic time'),
        ),
        migrations.AlterField(
            model_name='hostsstatistics',
            name='statistic_time',
            field=models.IntegerField(default=1733905243, verbose_name='Statistic time'),
        ),
        migrations.AlterField(
            model_name='timesavingstatistics',
            name='request_time',
            field=models.IntegerField(default=1733905243, verbose_name='Request time'),
        ),
    ]
