# Generated by Django 4.2.14 on 2024-12-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0010_alter_apivisitstatistics_request_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apivisitstatistics',
            name='request_time',
            field=models.IntegerField(default=1734315037, verbose_name='Request time'),
        ),
        migrations.AlterField(
            model_name='appvisitstatistics',
            name='statistic_time',
            field=models.IntegerField(default=1734315037, verbose_name='Statistic time'),
        ),
        migrations.AlterField(
            model_name='hostsstatistics',
            name='statistic_time',
            field=models.IntegerField(default=1734315037, verbose_name='Statistic time'),
        ),
        migrations.AlterField(
            model_name='timesavingstatistics',
            name='request_time',
            field=models.IntegerField(default=1734315037, verbose_name='Request time'),
        ),
    ]
